config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get 'sign_out', to: "users/sessions#destroy"
  end
  resources :users, only: [:show]
  resources :articles

  get 'home/index'
  get 'home/show'



  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ヘアカット研究所</title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<!-- /スクリプトを読み込む -->
<%= javascript_include_tag 'application' %>


  </head>

  <body class="body_color">

    <header>
      <div class="container">
        <div class="row">
          <small class="col-12">
            美容師向け、カット技術向上の為の学習サイト
         </small>
        <div></ br>
        <div class="row">

            <%= link_to  home_index_path do %>
                <span class="col-3 header_title">
                    <img src="/assets/haircut_lab_logo.png" alt="ヘアカット研究所ロゴ" width="auto" height="60">
                   ヘアカット研究所
                </span>
            <% end %>

     <!-- 1.ナビゲーションバーの設定 -->
          <nav class="navbar navbar-expand-lg navbar-dark bg-lighat">
                 <!-- 2.ヘッダ情報 -->
                    <a class="navbar-brand">メニュー</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="ナビゲーションの切替">
                      <span class="navbar-toggler-icon"></span>
                    </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ">
                    <% if user_signed_in? %>

                    Logged in as <storong><%= current_user.email %></storong>.
                        <%= link_to '記事エディット', new_article_path,  class:"" %>
                        <%= link_to 'プロフィール変更', edit_user_registration_path,  class:"" %>
                        <%= link_to 'ログアウト', sign_out_path,  class:"" %></li>
                      <% else %>
                        <%= link_to 'ホーム',  home_index_path,  class:"nav-item nav-link" %>
                        <%= link_to 'ヘアカット動画',  home_index_path,  class:"nav-item nav-link" %>
                        <%= link_to '会員登録', new_user_registration_path,  class:"nav-item nav-link" %>
                        <%= link_to 'ログイン', new_user_session_path,  class:"nav-item nav-link" %>
                    <% end %>
                </div>
              </div>
            </nav>
          </div>
        </div>


    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>


    <footer>
      <div class="container">
        <div class="row">
           <small class="mx-auto">
             Copyright (C) 2017 ヘアカット研究所.All Rights Reserved.
          </small>
        </div>
      </div>
    </footer>



    <%= debug(params) if Rails.env.development? %>







  </body>
</html>